Repository Field-Passer/Field-Passer-BE, pull requests merged in 2023-02, with the labels that each got.

#8 feat: 게시글 조회 기능 개발
  src/main/java/com/example/fieldpasserbe/post/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: Completed

#10 feat: 구장 종류, 지역, 구장명 리스트 조회 기능 구현
  src/main/java/com/example/fieldpasserbe/post/controller/CategoryController.java
  src/main/java/com/example/fieldpasserbe/post/controller/DistrictController.java
  src/main/java/com/example/fieldpasserbe/post/controller/StadiumController.java
  src/main/java/com/example/fieldpasserbe/post/dto/CategoryResponseDto.java
  src/main/java/com/example/fieldpasserbe/post/dto/DistrictResponseDto.java
  src/main/java/com/example/fieldpasserbe/post/dto/StadiumResponseDto.java
  src/main/java/com/example/fieldpasserbe/post/repository/CategoryRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/DistrictRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/StadiumRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/CategoryService.java
  src/main/java/com/example/fieldpasserbe/post/service/DistrictService.java
  src/main/java/com/example/fieldpasserbe/post/service/StadiumService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/CategoryServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/DistrictServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/StadiumServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: Completed

#11 feat: 회원 정보 상세 조회 기능 구현
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/dto/MemberDTO.java
  src/main/java/com/example/fieldpasserbe/admin/dto/MemberListDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/vo/MemberVO.java
  src/main/java/com/example/fieldpasserbe/member/entity/Member.java
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/fieldpasserbe/support/dto/PunishDTO.java
  src/main/java/com/example/fieldpasserbe/support/repository/PunishRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/support/service/PunishService.java
  src/main/java/com/example/fieldpasserbe/support/service/impl/PunishServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#12 feat: 게시글 작성, 수정, 삭제 구현
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/post/dto/PostRequestDto.java
  src/main/java/com/example/fieldpasserbe/post/entity/Post.java
  src/main/java/com/example/fieldpasserbe/post/repository/CategoryRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/DistrictRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/StadiumRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/PostService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#13 feat: 관심 게시글,구장 등록 구현 및 양도기간 지난 게시글 삭제 처리 구현
  src/main/java/com/example/fieldpasserbe/FieldPasserBeApplication.java
  src/main/java/com/example/fieldpasserbe/post/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/post/controller/StadiumController.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishFieldId.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishFieldRequest.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishPostId.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishPostRequest.java
  src/main/java/com/example/fieldpasserbe/post/entity/WishField.java
  src/main/java/com/example/fieldpasserbe/post/entity/WishPost.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/WishFieldRepository.java
  src/main/java/com/example/fieldpasserbe/post/repository/WishPostRepository.java
  src/main/java/com/example/fieldpasserbe/post/service/PostService.java
  src/main/java/com/example/fieldpasserbe/post/service/WishFieldService.java
  src/main/java/com/example/fieldpasserbe/post/service/WishPostService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/WishFieldServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/WishPostServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#14 refactor : 관리자 서비스 분리
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/dto/PeriodRequestDTO.java
  src/main/java/com/example/fieldpasserbe/admin/dto/PeriodResponceDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminLoginService.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminManageService.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminLoginServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminManageServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/vo/PeriodMemberVO.java
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
Labels: For: Backend, Priority: Medium, Type: Maintenance, Status: In Progress

#15 feat: 구장 종류별 마감 임박 게시글 출력 기능 구현
  src/main/java/com/example/fieldpasserbe/post/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#16 feat: 관리자 기능 다수 구현
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/dto/AdminLoginResponseDTO.java
  src/main/java/com/example/fieldpasserbe/admin/dto/PeriodResponseDTO.java
  src/main/java/com/example/fieldpasserbe/admin/dto/PostResponseDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminLoginServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/vo/AdminLoginVO.java
  src/main/java/com/example/fieldpasserbe/admin/vo/PeriodMemberVO.java
  src/main/java/com/example/fieldpasserbe/admin/vo/PostVO.java
  src/main/java/com/example/fieldpasserbe/admin/vo/PunishVO.java
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/entity/Category.java
  src/main/java/com/example/fieldpasserbe/post/entity/District.java
  src/main/java/com/example/fieldpasserbe/post/entity/Post.java
  src/main/java/com/example/fieldpasserbe/post/entity/Stadium.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
  src/main/java/com/example/fieldpasserbe/support/dto/PunishResponseDTO.java
  src/main/java/com/example/fieldpasserbe/support/entity/Report.java
  src/main/java/com/example/fieldpasserbe/support/repository/PunishRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/support/service/PunishService.java
  src/main/java/com/example/fieldpasserbe/support/service/impl/PunishServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#17 feat: 채팅 기능 일부 구현
  build.gradle
  src/main/java/com/example/fieldpasserbe/chat/conf/StompWebSocketConfig.java
  src/main/java/com/example/fieldpasserbe/chat/controller/ChatRoomController.java
  src/main/java/com/example/fieldpasserbe/chat/controller/StompChatController.java
  src/main/java/com/example/fieldpasserbe/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/example/fieldpasserbe/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/example/fieldpasserbe/chat/dto/ChatRoomRequestDto.java
  src/main/java/com/example/fieldpasserbe/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/example/fieldpasserbe/chat/entity/ChatMessage.java
  src/main/java/com/example/fieldpasserbe/chat/entity/ChatRoom.java
  src/main/java/com/example/fieldpasserbe/chat/repository/ChatMessageRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/chat/repository/ChatRoomRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/chat/service/ChatMessageService.java
  src/main/java/com/example/fieldpasserbe/chat/service/ChatRoomService.java
  src/main/java/com/example/fieldpasserbe/chat/service/Impl/ChatMessageServiceImpl.java
  src/main/java/com/example/fieldpasserbe/chat/service/Impl/ChatRoomServiceImpl.java
  src/main/java/com/example/fieldpasserbe/member/entity/Member.java
  src/main/java/com/example/fieldpasserbe/post/entity/Post.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#18 feat: 게시글 조회 기능 구현 및 관리자 기능 업데이트
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/dto/PeriodResponseDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/vo/PeriodMemberVO.java
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#19 refactor : 게시글 목록 확인 API에 날짜 체크 예외처리를 추가
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#21 feat: 관심 글 조회 및 관심 구장 조회 구현
  src/main/java/com/example/fieldpasserbe/post/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/post/controller/StadiumController.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishFieldRequestDto.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishFieldResponseDto.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishPostRequestDto.java
  src/main/java/com/example/fieldpasserbe/post/dto/WishPostResponseDto.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/WishFieldRepository.java
  src/main/java/com/example/fieldpasserbe/post/repository/WishPostRepository.java
  src/main/java/com/example/fieldpasserbe/post/service/PostSearchService.java
  src/main/java/com/example/fieldpasserbe/post/service/WishFieldService.java
  src/main/java/com/example/fieldpasserbe/post/service/WishPostService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostSearchServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/WishFieldServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/WishPostServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: In Progress

#22 refactor: 10분마다 양도시간 지난 게시글 삭제 처리 코드 수정
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostServiceImpl.java
Labels: For: API, Priority: Low, Type: Feature, Status: Completed

#23 feat: 게시글 블라인드 기능 구현중
  .gitignore
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/dto/BlindRequestDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminManageService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminManageServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/service/PostService.java
  src/main/java/com/example/fieldpasserbe/post/service/impl/PostServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Type: Idea, Status: In Progress

#25 feat: 멤버 기능 구현
  .gitignore
  .idea/compiler.xml
  .idea/vcs.xml
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/com/example/fieldpasserbe/member/controller/MemberController.java
  src/main/java/com/example/fieldpasserbe/member/dto/MailDTO.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberDTO.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberInfo.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberUpdate.java
  src/main/java/com/example/fieldpasserbe/member/entity/Member.java
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/member/service/EmailService.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/EmailServiceImpl.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
Labels: For: API, Priority: Critical, Type: Feature, Status: In Progress

#26 conf: 코드 통합 완료
  .gitignore
  build.gradle
Labels: For: Backend, Priority: Critical, Type: Idea, Status: In Progress

#27 ref: 로그인 데이터 반환값 responseDTO로 반환 할 수 있게 코드 수정
  build.gradle
  src/main/java/com/example/fieldpasserbe/global/response/ErrorResponseDTO.java
  src/main/java/com/example/fieldpasserbe/global/response/ResponseDTO.java
  src/main/java/com/example/fieldpasserbe/member/controller/MemberController.java
  src/main/java/com/example/fieldpasserbe/member/dto/MailDTO.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberDTO.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberDelete.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberUpdate.java
  src/main/java/com/example/fieldpasserbe/member/service/EmailService.java
  src/main/java/com/example/fieldpasserbe/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/EmailServiceImpl.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
Labels: For: Backend, Priority: Medium, Type: Maintenance, Status: Completed

#32 Feat: 게시글 블라인드 처리 기능 구현
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminManageServiceImpl.java
  src/main/java/com/example/fieldpasserbe/post/entity/Post.java
Labels: For: API, Priority: Medium, Type: Feature, Status: Completed
