Repository Field-Passer/Field-Passer-BE, pull requests merged in 2023-01, with the labels that each got.

#4 feat: 엔티티 생성 및 연관관계 설정
  build.gradle
  src/main/java/com/example/fieldpasserbe/seok/controller/PostController.java
  src/main/java/com/example/fieldpasserbe/seok/dto/PostListResponseDto.java
  src/main/java/com/example/fieldpasserbe/seok/entity/CategoryList.java
  src/main/java/com/example/fieldpasserbe/seok/entity/DistrictList.java
  src/main/java/com/example/fieldpasserbe/seok/entity/Member.java
  src/main/java/com/example/fieldpasserbe/seok/entity/Post.java
  src/main/java/com/example/fieldpasserbe/seok/entity/StadiumList.java
  src/main/java/com/example/fieldpasserbe/seok/entity/TransactionStatus.java
  src/main/java/com/example/fieldpasserbe/seok/repository/CategoryListRepository.java
  src/main/java/com/example/fieldpasserbe/seok/repository/DistrictListRepository.java
  src/main/java/com/example/fieldpasserbe/seok/repository/MemberRepository.java
  src/main/java/com/example/fieldpasserbe/seok/repository/PostRepository.java
  src/main/java/com/example/fieldpasserbe/seok/repository/StadiumListRepository.java
  src/main/java/com/example/fieldpasserbe/seok/service/PostService.java
  src/main/java/com/example/fieldpasserbe/seok/service/impl/PostServiceImpl.java
Labels: For: Backend, Priority: Medium, Type: Feature, Status: Completed

#3 FEAT : 관리자 서비스 기능 다수 구현
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/create-backlog.md
  .gitignore
  .idea/.name
  .idea/compiler.xml
  build.gradle
  src/main/java/com/example/fieldpasserbe/lee/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/lee/admin/dto/AdminLoginRequestDTO.java
  src/main/java/com/example/fieldpasserbe/lee/admin/dto/AdminLoginResponceDTO.java
  src/main/java/com/example/fieldpasserbe/lee/admin/dto/MemberListDTO.java
  src/main/java/com/example/fieldpasserbe/lee/admin/entity/Admin.java
  src/main/java/com/example/fieldpasserbe/lee/admin/repository/AdminRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/lee/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/example/fieldpasserbe/lee/admin/vo/AdminLoginVO.java
  src/main/java/com/example/fieldpasserbe/lee/admin/vo/MemberListVO.java
  src/main/java/com/example/fieldpasserbe/lee/admin/vo/SimpleVO.java
  src/main/java/com/example/fieldpasserbe/lee/board/entity/Board.java
  src/main/java/com/example/fieldpasserbe/lee/board/entity/Category.java
  src/main/java/com/example/fieldpasserbe/lee/board/entity/District.java
  src/main/java/com/example/fieldpasserbe/lee/board/entity/Stadium.java
  src/main/java/com/example/fieldpasserbe/lee/board/entity/UsageTime.java
  src/main/java/com/example/fieldpasserbe/lee/board/repository/BoardRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/board/repository/CategoryRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/board/repository/DistrictRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/board/repository/StadiumRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/board/service/BoardService.java
  src/main/java/com/example/fieldpasserbe/lee/board/service/impl/BoardServiceImpl.java
  src/main/java/com/example/fieldpasserbe/lee/member/entity/Member.java
  src/main/java/com/example/fieldpasserbe/lee/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/member/service/MemberService.java
  src/main/java/com/example/fieldpasserbe/lee/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/Answer.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/Punish.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/PunishPeriod.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/Question.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/QuestionCategory.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/QuestionProccess.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/Report.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/ReportCategory.java
  src/main/java/com/example/fieldpasserbe/lee/support/entity/ReportProcess.java
  src/main/java/com/example/fieldpasserbe/lee/support/repository/PunishRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/lee/support/service/PunishService.java
  src/main/java/com/example/fieldpasserbe/lee/support/service/impl/PunishServiceImpl.java
Labels: For: Backend, Priority: Medium, Type: Feature, Status: In Progress

#5 feat: member Entity 설계
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/example/fieldpasserbe/kim/entity/MemberEntity.java
Labels: For: Backend, Priority: High, Type: Feature, Status: In Progress
