Repository Field-Passer/Field-Passer-BE, pull requests merged in 2023-03, with the labels that each got.

#38 Refactor: 관리자 로그인 기능 수정 및 반환 상태코드 수정
  src/main/java/com/example/fieldpasserbe/admin/controller/AdminController.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminManageService.java
  src/main/java/com/example/fieldpasserbe/admin/service/AdminService.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminLoginServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminManageServiceImpl.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminServiceImpl.java
Labels: For: API, Priority: High, Type : Bug, Status: Completed

#39 Refactor: memberId 보여줄 수 있게 코드 수정
  src/main/java/com/example/fieldpasserbe/member/controller/MemberController.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberDTO.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberInfo.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberUpdate.java
  src/main/java/com/example/fieldpasserbe/member/dto/MemberUpdatePassword.java
  src/main/java/com/example/fieldpasserbe/member/service/impl/MemberServiceImpl.java
Labels: For: Backend, Priority: Low, Type: Maintenance, Status: Completed

#40 Refactor: 네이티브 쿼리 수정
  .gitignore
  .idea/vcs.xml
  src/main/java/com/example/fieldpasserbe/member/repository/MemberRepositoryJPA.java
  src/main/java/com/example/fieldpasserbe/post/repository/PostRepositoryJPA.java
Labels: For: Backend, Priority: Medium, Type: Maintenance, Status: Completed

#42 refactor: 관리자 블라인드 처리 기능 수정
  src/main/java/com/example/fieldpasserbe/admin/dto/BlindRequestDTO.java
  src/main/java/com/example/fieldpasserbe/admin/service/impl/AdminManageServiceImpl.java
Labels: For: API, Priority: Medium, Type: Feature, Status: Completed
